### ISSUE TITLE
About reproduce the results in paper.

### ISSUE THREAD

**Issue by lucasliunju** [nbasyl/DoRA#3]
Hi, thank you very much for your great paper.

I would like to reproduce the results in your paper and would like to ask do you have some recommendations about the codebase of PEFT. The main reason is that I find the results are pretty different for the same method in different paper. 

Thank you very much in advance.

**Comment by nbasyl** [comment]
Hi, Thanks for your interest, may I know which results are you referring to? Could you provide more details on " I find the results are pretty different for the same method in different paper."

**Comment by lucasliunju** [comment]
Hi, thanks for your reply.

I have reproduced the results of table 1. 

For " I find the results are pretty different for the same method in different paper.", I found some paper uses a similar method (fine-tune llama with lora) but the results on the tasks of huggingface leaderboard are different. So I guess the codebase is important.

**Comment by nbasyl** [comment]
Yes, codebase is important as different prompt formats will often lead to different evaluation results.

**Comment by lucasliunju** [comment]
Hi, May I ask a question that is not related to your paper. 

I woulk like to ask: What is the main problem of lora-based methods?

**Comment by nbasyl** [comment]
In my opinion, numerous difficulties persist, including overfitting and hyperparameters searching, compatibility with compression techniques, and many more issues that could be mentioned.
